version: "2.1"
services:
  client:
    build: frontend
    ports:
      - 3000:3000
    environment:
      - BASE_URL=server:8080/
  server:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/your_drive?allowPublicKeyRetrieval=TRUE&useSSL=false
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=root
  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=your_drive
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=app_user
    healthcheck:
      test: '/usr/bin/mysql --user=app_user --password=root --execute "SHOW DATABASES;"'
      timeout: 5s
      interval: 2s
      retries: 10
    volumes:
      - my-datavolume:/var/lib/mysql
      - ./backend/src/main/resources/db/migration/V1.0__Create.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  my-datavolume:
