#!/bin/bash
echo "$docker_password" | docker login -u "$docker_user" --password-stdin
docker build -t "$docker_user"/frontend frontend 
docker build -t "$docker_user"/backend backend 
docker push "$docker_user"/frontend
docker push "$docker_user"/backend